apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "btc-loki-helm.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "btc-loki-helm.labels" . | nindent 4 }}
data:
  local-config.yaml: |
{{ toYaml .Values.config | indent 4 }}
