apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "btc-loki-helm.fullname" . }}
  labels:
    {{- include "btc-loki-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "btc-loki-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "btc-loki-helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: loki
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-config.file=/etc/loki/local-config.yaml"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/loki
            - name: storage
              mountPath: /loki
      volumes:
        - name: config
          configMap:
            name: {{ include "btc-loki-helm.fullname" . }}
        - name: storage
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "btc-loki-helm.fullname" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
